server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}

management:
  security:
    enabled: false
  endpoint: 
    health:
      show-details: always
    shutdown: 
      enabled: true
    env:
      enabled: true
  endpoints: 
    web: 
      exposure: 
        include: 
        - env
        - info  
        - health  
        - shutdown
        - scheduledtasks
        - auditevents

feign:
  hystrix:
    enabled: true

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  semaphore:
    maxSemaphores: 30000  

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

hystrix:
  shareSecurityContext: true
  command:
    default:
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 2000
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: "SEMAPHORE"
          thread:
            timeoutInMilliseconds: 120000
          semaphore:
            maxConcurrentRequests: 2000  

---
spring:
  profiles: localhost   
      
---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
