server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
---
spring:
  profiles: docker

eureka:
  instance:
    hostname: eureka
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
